# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bootcamp-dci',
                'doc_host': 'https://dci-courses.github.io',
                'git_url': 'https://github.com/dci-courses/bootcamp-dci',
                'lib_path': 'bootcamp_dci'},
  'syms': {'bootcamp_dci.core': {'bootcamp_dci.core.foo': ('core.html#foo', 'bootcamp_dci/core.py')}}}
